version: "3.7"
services:
  build_http_driver:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        METABASE_VERSION: v0.45.3
        CLOJURE_VERSION: 1.11.1.1252
    volumes:
      - ./:/build
